### ISSUE TITLE
Usage of userlist_push? 

### ISSUE THREAD

**Issue by richardonrails** [userlist/userlist-rails#8]
I'm trying to use `userlist_push?` on my User and Company models to avoid sending `status: :disabled` accounts to Userlist.

My users all start out as active and then get disabled if they appear to be spam signups. I also set up Userlist to exclude disabled users in my campaigns (but I'd really like those users deleted, hence using `userlist_push?`).

The problem is that `userlist_push?` is preventing pushing any updates to Userlist for existing profiles, so Userlist still sees those users as active instead of disbaled.

I suppose the solution is to stop using `userlist_push?` and I have to figure out some other way to manually delete profiles in Userlist once they become disabled in my system?

**Comment by benedikt** [comment]
Hey @richardonrails!

You can still use `userlist_push?` to prevent future updates, but you probably also want to delete users from Userlist using `Userlist::Push.users.delete(user)` when they get disabled. 

Depending in your implementation, you can either do that in the method that disables users or as an `after_save` callback. 

Using a method: 

```ruby
def disable!
  update(status: :disabled) 
  Userlist::Push.users.delete(self)
end
```

Using a callback:
```ruby 
after_save :delete_disabled_users 

def delete_disabled_users 
  return unless saved_change_to_status?(to: :disabled)

  Userlist::Push.users.delete(self)
end
```

Does that help?

**Comment by richardonrails** [comment]
Yes that helps, a callback is what I needed, thank you! Since it's the Company that gets disabled, I did this on my company model:

```rb
  after_save :delete_disabled_from_userlist

  def delete_disabled_from_userlist
    return unless saved_change_to_status?(to: 'disabled')

    self.users.each do |user|
      Userlist::Push.users.delete(user)
    end
    Userlist::Push.companies.delete(self)
  end
```

(Looks like I had to make 'disabled' a string for this to work even though it's an enum hash)

By the way I wish I could easily switch to a development environment in Userlist to test changes...
